viewstools/morph

__tests__/__snapshots__/react.js.snap
__tests__/views/ListOfButtons.view
morph/react-native/block-wrap.js
morph/react/make-visitors.js

fix: lists of buttons add the key prop to the correct wrapper element for react-native

---

__tests__/__snapshots__/react.js.snap
__tests__/views/UseText.view
morph/react-native/get-style-for-property.js

Addresses this https://github.com/viewsdx/morph/issues/8
Open to suggestions on what to do if no font size is supplied

Fix: Line height on native

---

__tests__/views/BoxShadow.view
parse/helpers.js

fixes https://github.com/viewsdx/morph/issues/9

feat: allow template literals containing expressions without backticks

---

.prettierrc
__tests__/__snapshots__/react.js.snap
__tests__/views/Scope.view
morph/react/make-block-test-id.js
morph/utils.js
package.json

Renaming output of test ids to append the scope at the end of the id. Implements the first part of #42.

Automation tests

---

__tests__/__snapshots__/react.js.snap
__tests__/react.js
cli.js
morph/e2e.js
morph/e2e/block.js
morph/e2e/to-file.js
morphers.js
restricted-names.js
watch.js

Feature: creating file with components for e2e tests

E2e phase2

---

__tests__/views/Action.view
__tests__/views/Form.view
__tests__/views/NestedRoutes.view
__tests__/views/Print.view
__tests__/views/ProxyTest.view
__tests__/views/ScopePopup.view
__tests__/views/ScopePopup2.view
__tests__/views/Test.view
__tests__/views/TestIds.view
__tests__/views/UseProxy.view
__tests__/views/UseSvg.view
__tests__/views/UseTextCustomFont.view
parse/__snapshots__/index.test.js.snap
parse/index.js
parse/index.test.js

https://github.com/viewstools/docs/issues/6

Blocks syntax

---

CONTRIBUTING.md

Command on step 4 works fine for react-web, but not for react-native. 
Just adding that command.

[ENHANCEMENT] Adding command for react-native watch

---

__tests__/__snapshots__/react.js.snap
morph/e2e/block.js

https://github.com/viewstools/morph/issues/46

Fix: E2e top level element

---

morph/__snapshots__/inline-svg.test.js.snap
morph/svg-to-view.js

https://github.com/viewstools/morph/issues/72

Fix: SVG groups

---

morph/font.js
morph/react-dom/morph-font.js
morph/react-native.js
morph/react-native/morph-font.js
morph/react-native/morph-fonts.js
morph/react/get-dependencies.js
morph/utils.js
watch.js

https://github.com/viewstools/morph/issues/24

Include morphed fonts on native

---

__tests__/__snapshots__/react.js.snap
__tests__/views/TextInterpolation.view
morph/react/property-text.js
morph/utils.js
parse/helpers.js
parse/index.js

https://github.com/viewstools/morph/issues/56
Things got a bit complicated when I allowed for interpolation inside scoped conditions. It works but it's a bit wacky 🙈

Text interpolation

---

ensure-local-container.js

Use single quotes in line with our prettier set up.

fix: use single quotes in local container

---

__tests__/__snapshots__/react.js.snap
__tests__/views/ListWithKey.view
morph/react-dom/block-properties.js
morph/react-native/block-properties.js
morph/react/block-in-list.js
morph/react/block-list.js
morph/react/property-rest.js

To specify a key other than the index in the list, add a key prop to the card:
```
List
from <
Card
key id
```

feat: let list cards specify its key, default to index in list

---

__tests__/__snapshots__/react.js.snap
__tests__/views/ListOfSomething.view
morph/react-dom/get-style-for-property.js
morph/react-native/get-style-for-property.js
morph/utils.js

https://github.com/viewstools/morph/issues/110
TODO: After merging, update version number on [corresponding codemod](https://github.com/viewstools/codemods/compare/camel-case-props)

Use camel case props

---

__tests__/__snapshots__/react.js.snap
__tests__/views/HyphenatedProps.view
parse/helpers.js
parse/index.js

Not ideal, I'm duplicating stuff across the parser and the morpher but hey, it's temporary 🙃

Ensure props are converted to hyphenated

---

__tests__/__snapshots__/react.js.snap
__tests__/views/DynamicFontProps.view
morph/react-native/get-style-for-property.js
morph/react/property-style.js

Fixes https://github.com/viewstools/morph/issues/127

Fix: dynamic font props on native

---

__tests__/__snapshots__/react.js.snap
__tests__/views/Scope.view
__tests__/views/SlotOnBaseAndValueOnScope.view
morph/utils.js

https://github.com/viewstools/morph/issues/119

Fix: Duplicated keys on scoped open slots 

---

parse/__snapshots__/index.test.js.snap
parse/index.js
parse/index.test.js
yarn.lock

https://github.com/viewstools/morph/issues/149
scratching my own itch 😛

feat: add warning for multiple prop values

---

__tests__/__snapshots__/react.js.snap
__tests__/views/DynamicWidth.view
morph/utils.js

Now we can pass through values other than straight numbers :)

feat: allow users to pass property units dynamically

---

cli.js

- removes experimental-json-modules flag which was preventing the autogeneration of view.js files

remove experimental json module

---

morph-all-view-graphql-files.js

Related to https://github.com/orgs/viewstools/teams/core/discussions/7

feat: morph/react extend data pattern with onChange/onSubmit handlers

---

morph/react-dom.js
morph/react/block-list.js
morph/react/get-body.js
morph/react/get-dependencies.js
morph/react/to-component.js
package.json
views/ViewsData.js
yarn.lock

Here is a small PR to wrap List items in a DataProvider so that we don't have to explicitly define it anymore. Let me know please if you have any suggestions on how that could be improved. Thanks!

feat: morph/react add data provider for list items

---

morph/react/get-body.js
morph/utils.js

* pass scope's prop to correctly identify the data key to be assigned

fix: morph/react fix assigning data value to when condition

---

morph/utils.js

* also add better support for negative data value references

fix: morph/react fix slot check for goTo action

---

morph/react/block-in-list.js
morph/react/block-list.js
morph/react/block-set-flow-to-based-on-data.js

* also removed unused code related to set flow

fix: morph/react allow using null or undefined values in list

---

views/Data.js
views/Data.tools.js

For whatever reason immer just complained about the [Set](https://immerjs.github.io/immer/complex-objects) now on a new project 🤷‍♂️ . Anyway, this moves the proxy to be created adhoc as the reducer runs the changes.

fix: views/Data/use immer inside the reducer to change the value only

---

morph/react-dom/get-style-for-property.js
morph/react-dom/morph-font.js

External configuration will come in another PR

fix: add sans-serif font fallback. 

---

morph/react-dom/morph-font.js

See: https://developers.google.com/fonts/docs/css2

fix: the format of the call to css2 has changed

---

morph/react-dom/get-value-for-property.js
morph/react/properties-design-token.js
morph/utils.js
parse/index.js

* issue caused because it didn't check data usage in when conditions as those are part of scopes instead of block's properties

fix: morph/react fix issue preventing using condition based on data

---

get-view-relative-to-view.js
morph/react-dom.js
morph/react-dom/block-views-flow.js
morph/react-dom/block.js
morph/react-native.js
morph/react/get-body.js
morph/react/get-expanded-props.js
parse/index.js

This approach seems to work and it will create the same output as the changes we did on Friday in `DropdownFlow` DS component (as I tested it, it still worked fine).
**Note:** I just noticed the flow sync through Tools doesn't work anymore, I'll try to see if I can figure out a way to make it work with sub-flows.

feat: morph/react add support for flow to design system views

---

ensure-is-media.js

Fix initial value for media variables (it was set to `false` by default) and simplify the implementation by getting rid of the used library.

fix: media behavior by getting rid of a library
