CONTRIBUTING.md
the Contribute guide tells us to do `yarn link views-morph` which gives the following error:
`error No registered module found called "views-morph".`
Apparently the module changed name at some point so now the following command is the one that works for me @dariocravero 
`yarn link @viewstools/morph`
=> [FIX] deprecated name on yarn link

__tests__/__snapshots__/react.js.snap, morph/react-dom/properties-style.js
Leverage emotion's special `label` key to enable descriptive CSS classes
that would append the block's name after the randomly generated class.
https://emotion.sh/docs/labels
=> feat: add label to generated CSS

__tests__/__snapshots__/react.js.snap, __tests__/views/AnimatedButton.view, morph/react-dom.js, morph/react-dom/get-block-name.js, morph/react-dom/properties-style.js, morph/react-native.js, morph/react-native/maybe-uses-animated.js, morph/react-native/properties-style.js, morph/react/get-animated-value.js, morph/react/get-body.js, morph/react/get-dependencies.js, morph/react/restricted-names.js, morph/react/to-component.js, morph/utils.js, parse/__snapshots__/index.test.js.snap, parse/helpers.js, parse/index.js
This PR fixes #112, #98 and #108. It also supports `Timing` animations in native and fixes `delay` on DOM since `react-spring` supports it already. It also fixes `easeInOut`.
To wrap up animations, I'd say we're missing the following:
- support spring on `hover` #107,
- add `onAnimationDone` callback #111,
- add `before` and `after` system scopes - this should allow for in/out transitions, and
- stagger cards in lists.
The last two can be done with a logic layer in JS so I wouldn't say there's a lot of rush on them.
Am I missing anything @amymc, @tombrewsviews?
NOTE: After releasing this version, we'd need to update `@viewstools/use` to add `@viewstools/animations` as a dependency.
=> Animations 2

parse/__snapshots__/index.test.js.snap, parse/index.js
https://github.com/viewstools/morph/issues/87
Not sure if this is exactly what we want...
If a user passes a `when` or an `onWhen` with no value they just get ignored, but the following properties are morphed as though they're not scoped. 
So for example, this view: 
```
Label Text
height 10
when
height 20
color
text
backgroundColor < red
```
becomes this:
```
const Label = css({
label: 'Label',
height: 20,
backgroundColor: 'var(--backgroundColor)',
});
const Empty = props => {
return (
<span
data-test-id={`${props['data-test-id'] || 'Label'}|`}
style={{ '--backgroundColor': props.backgroundColor }}
className={`views-block ${Label}`}
/>
);
};
Empty.defaultProps = { backgroundColor: 'red' };
export default Empty;
```
So the second value for `height` overwrites the first. I suppose, ideally …
=> Fix: don't morph empty props

morph/react/to-component.js
This PR adds a comment on the top of each `.view.js` file.
Close #27 
cc @dariocravero
=> feat: add autogenerated comment on each .view.js file

views/ViewsData.js
I think this was imported automatically when we implemented it, it seems to actually be missing from the original file.
=> fix: ViewsData add missing useFlow import

views/ViewsData.js
* this will allow us to update the data after submit completed
I gave it a try and implemented this option to pass an `onChange` function as an argument of `onSubmit` so that we could update some data (e.g. clearing some data as we've seen yesterday). I tested that against the implementation of pay now functionality and seemed to behave as expected. Let me know if you see any issues with this approach please. Thanks
=> feat: morph/react provide change function for onSubmit action

morph/react-dom/block-properties.js, morph/react-native/block-properties.js
Neil correctly pointed out that we get an error in regard to `itemDataContextName` not being a recognized React props. It was happening due to it being passed to the React components - added this check so that it will be ignored.
=> fix: morph/react prevent passing itemDataContextName as props

morph/react-dom.js, morph/react-dom/block-go-to.js, morph/react-dom/block.js, morph/react-dom/get-value-for-property.js, morph/react-native.js, morph/react-native/get-value-for-property.js, morph/react/block-add-data.js, morph/react/block-list.js, morph/react/block-off-when.js, morph/react/get-body.js, morph/react/property-text.js, morph/utils.js, parse/helpers.js, parse/index.js
This is the first iteration in declaring data at the block level in addition to the existing view level one. I had a chat with Tom about it and he said he would prefer to still have the option to declare data at the view level (as we do now) so that it can be reused in multiple places if needed. I think it should be advised to define the data as close to where it is used as possible, so I wouldn't see it being used very frequent anymore. If we see the view level data is not necessary we could completely remove that option in a next release I think, but for now I think it could be useful.
If `data` was defined both at the view level and at the block level the closest one (block level will take priority), for example:
```
Person View
data person.first_name
Text
data person.last_name
text …
```
=> feat: morph/react declare data at the block level

morph/react-dom/block.js, views/ViewsData.tools.js
* this change was probably removed due to a bad merge conflicts
Added also a fix for an issue I encountered with `onWhen`s as the data block logic should be executed before it.
=> fix: morph/react change onSubmit arguments to be an object

morph/utils.js
There was this check I missed which ended up interpreting the data value as text rather than a variable. Not sure if this is the best approach to check if it contains `Data.`, let me know if you think we can handle it in a better way. thanks
=> fix: morph/react check if a prop value references data

morph/react-dom/block-go-to.js, morph/react-dom/get-value-for-property.js, morph/react-native/get-value-for-property.js, morph/react/block-add-data.js, morph/react/block-list.js, morph/react/block-off-when.js, morph/react/get-body.js, morph/react/property-text.js, morph/utils.js, parse/index.js
There is this use case for which it seems to always get the `value` from props instead of grabbing the data key:
```
Something View
is together
Horizontal
backgroundColor red
data social_link.link
when <value
backgroundColor blue
```
the code generated looks something like this:
```
style={{'--backgroundColor': value ? "rgb(53,80,164)" : "rgba(53,80,164,0.85)"}}
```
where the value is referenced from the props of the component.
I didn't find any usage of `when <value` in our codebase, so I am not sure if this is even a valid case. Do you think it should actually work and point to data path in this case?
=> feat: morph/react support multiple data keys per block

morph/react/block-add-data.js, parse/helpers.js
With these changes it should support constant values for data keys e.g.
```
data 10
format age
```
or
```
data "Hello World"
```
or
```
data 'Hello World'
```
=> feat: morph/react support data keys with constant values

morph/react/get-body.js, morph/react/get-expanded-props.js, morph/react/property-event-handler.js
@dariocravero I reverted it to the initial implementation because some of the params have default values assigned and this will result in a syntax error. Let me know please if you have an idea how to best handle it
=> fix: morph/react pass viewPath as a param to function

morph/react-dom/get-value-for-property.js, morph/react-native/get-value-for-property.js, morph/react/block-off-when.js, morph/utils.js
* allow props to start with data reserved keywords e.g. valueSomething
There was a partial match on those keywords and as a result, as Neil discovered, it will end up referencing a data value instead of a prop e.g.
```
data some.data
selected <
text <valueSomething
```
it will be morphes as:
```
...
text={someData.valueSomething}
```
=> fix: morph/react match data property exactly

morph-all-view-graphql-files.js, morph/react/block-add-data.js, morph/react/block-list.js, morph/react/get-body.js, parse/helpers.js, views/Data.js, views/Data.tools.js
As this includes quite some changes in the applications to remove the context name from the data providers paths, I decided to address the next step in another PR rather than make all the changes in one go (i.e. extracting distinct hooks for different actions allowed to be done on data like `useDataValue`, `useDataFormat`, `useDataValidate` etc.).
=> feat: morph/react remove context name from data path

views/Data.js
I found out I made the change in `Data.tools.js` but didn't apply it to `Data.js` too. Due to that, filtering the comms threads based on status worked fine locally, but when I tested it on staging I got an error. Do you have any strategy to test these changes locally to make sure the 2 files are in sync?
=> fix: morph/react pass data value to formatOut function

morph/react/block-add-data.js, morph/utils.js, parse/helpers.js, parse/index.js
I tried to update the morphing of the data blocks so that instead of making use of the old `useData` function it will utilise the new granular functions which will be added in the other PR.
=> feat: morph/react make use of granular functions when morphing data block

morph/react-dom/block.js, morph/react-native/block.js, morph/react/block-set-flow-to-based-on-data.js, parse/index.js, views/Data.js, views/Data.tools.js
For now I let the keyword to be `data` as it seems people don't see it as a problem. We can go back to it and rename it if we find any issue.
Here is a small example for how that will look like:
```
LocationChooser View
is separate
data selected.parent_company_id
No
Content
```
=> feat: morph/react support set flow based on data on separate views

morph/react/block-set-flow-to-based-on-data.js, parse/index.js, views/Data.js, views/Data.tools.js
I just realised I forgot to rename the `checkInitial` param to `validateInitial` as discussed.
=> fix: morph/react rename param checkInitial to validateInitial

views/Data.js, views/Data.tools.js
Due to using `useDataFormat` on the `useSetFlowToBasedOnDataSwitch` and sometimes no `format` function is provided (the view is derived straight from the data value) it would show some warnings in dev mode. Rather than passing the `__ignoreMissingInDevMode` flag to suppress those warnings I think it makes more sense to just have a default function (this is effectively what the logic does anyway, so I think it even makes the code more explicit).
=> fix: morph/react prevent warnings in dev mode due to missing format

make-get-system-import.js, morph/react-dom.js, morph/react-dom/block-properties.js, morph/react-dom/get-style-for-property.js, morph/react-dom/properties-style.js, morph/react-native.js, morph/react/block-add-data.js, morph/react/properties-design-token.js, morph/utils.js, parse/get-tags.js, parse/index.js, views/DesignTokens.js, views/DesignTokens.tools.js
With these change support was added for design tokens. In order the make use of the design tokens an application should be wrapped by the `ThemeDesignTokensProvider` like this:
```
import design_tokens from 'DesignSystem/design-tokens.json'
<ThemeDesignTokensProvider
theme="light"
design_tokens={design_tokens}
>
...
</ThemeDesignTokensProvider>
```
Let me know if you think this approach is not right or there is a better way and we can discuss.
Here are a couple of cases supported with this approach:
```
backgroundColor dt.colors.primary
```
morphed as:
```
let dtColorsPrimary = fromData.useDesignTokenValue({ viewPath, path: 'colors.primary' })
...
style={{'--backgroundColor': dtColorsPrimary}}
...
```
```
backgroundColor < dt.colors.primary
```
morphed as:
```
... // other props …
```
=> feat: morph/react add support for design tokens

morph/react/block-list.js
Added also a check if the item has an id, if the developer didn't provide a custom key. But I am not sure this is the right approach, as it will end up shipping additional code to production as well. Let me know please if you think there is a better approach to perform this check.
=> feat: support custom keys for items in a list

morph/react/block-in-list.js, morph/react/block-list.js, morph/utils.js
A made a small change as the `viewPath` of an item in a list was still `item?.id || index`, I think it makes more sense to be consistent and use the same generated key.
=> fix: include list item key in the view path of the list elements

morph/react/block-list.js, morph/react/get-body.js
I completely forgot we're using List also in DS for some projects, so code morphed has a syntax error as the iterator function doesn't have a return statement. I moved the warning displayed when the items in the list don't have an id inside the ListItem component and with that approach it should work fine.
=> fix: prevent syntax error when using list component in design system

views/Data.js, views/Data.tools.js
@CamilaSau came up with a use case requiring comparing the current with the previous value on the onSubmit function and she proposed to pass the originalValue as a param in addition to the current value. I think it makes sense, so added this small PR, but let me know if there is anything I may have missed
=> feat: pass originalValue as a param to DataProvider's onSubmit function

morph/react-native/properties-style.js
With these changes the morpher will ignore the style properties that are not valid for React Native's Text and View components.
=> fix: ignore react native invalid style props

morph/react-native/properties-style.js
I fixed it to also apply the filter on the dynamic styles as it didn't work as expected on the `Info` component from the DS:
```
Info View
Info Text
...
textOverflow < ellipsis
```
Also I changed the check to make use of `node.name` as in this case the `node.is` was `Info` and it wouldn't apply this rule. Let me know if you think it makes sense or I may have missed something.
=> fix: ignore react native invalid props from dynamic styles

morph/react-native.js
e.g. it will generate something like this for the views with a No/Content/Loading/etc. pattern:
```
import Content from './Content/view.js'
import Empty from './Empty/view.js'
import Error from './Error/view.js'
import Loading from './Loading/view.js'
import No from './No/view.js'
import React from 'react'
export default function Content({....
```
hence throwing an error as the component name is `Content` and there is already an import `Content`. It works fine already for react-dom
=> fix: prevent issue with component name already used in import

morph/react/get-body.js
Sometimes I found that for animations it was referencing the props through e.g. `props.isInvalid` instead of directly referencing the expanded prop so it results in an error as props is not defined.
=> fix: reference expanded props from animation scoped conditions

morph/react-dom/get-value-for-property.js, morph/react-native/get-value-for-property.js
* the client using this method will have to always get the value from the onChange's second param for the code to work the same way regardless of the target platform
=> fix: add value param to onChange for react native TextInput

make-get-system-import.js, morph/react-native/get-value-for-property.js, morph/react/get-body.js, morph/react/get-dependencies.js, morph/react/get-use-is-focused.js, views/hooks/useIsFocused.js
As suggested, I followed the same approach as for `isHovered` and with these changes it should enable making use of `isFocused` conditions in animations.
=> fix: custom hook to record if input field is focused

morph/react-native/get-block-name.js
If a node is animated, but the component is not wrapped into react-spring's `animated` method it throws an error that a freezing object cannot be updated. As I found out I think we didn't apply this change for the TextInpur RN component, it's only applied for Text one.
=> fix: wrap TextInput in animated if necessary

morph/react/make-get-import.js
* will enable importing platform specific files such as `Logic.native.js` for React Native
With this change, the import of the files generated by the morpher will look something like this:
```
import Logic from './logic'
import View from './view'
```
so for React Native, if there is a file named `logic.native.js` it will be picked up by default. I did some testing by following the RN documentation here https://reactnative.dev/docs/platform-specific-code#native-specific-extensions-ie-sharing-code-with-nodejs-and-web.
Let me know if you think it may pose any issues in other circumstances, and an alternative I think is to pass a startup flag if for an application we want to preserve the import with file extension.
=> feat: import module without `.js` extension
